### ISSUE TITLE
transform_quantile_to_pmf

### ISSUE THREAD

**Issue by elray1** [reichlab/idforecastutils#10]
Similar to our previous `get_pmf_forecasts_from_quantile` function, but focusing on the logic of doing the output type conversion. This function will be less specific to flu, and will not handle the logic of getting bin endpoints.

Proposed signature:
```
#' Transform model outputs from the quantile `output_type` to the pmf
#' `output_type`.
#'
#' @param model_out_tbl An object of class `model_out_tbl` containing
#' predictions of quantile `output_type`
#' @param bin_endpoints A data frame with columns:
#'   - `output_type_id`: character or numeric vector of labels for each bin or
#'     category
#'   - `lower`: numeric vector of lower endpoints for each bin
#'   - `upper`: numeric vector of upper endpoints for each bin
#' Optionally, this data frame may also contain other columns matching task id
#' variables in `model_out_tbl`, if the bin endpoints differ depending on the
#' prediction task (e.g. for different locations).
#' @param tail_dist: String specifying the distribution to use for
#' extrapolation into the tails of the predictive distribution. See the details
#' for more information.
#'
#' @details Bin probabilities are calculated by taking a difference of values of
#' the estimated CDF at the lower and upper endpoints of each bin. This means
#' that probabilities are for half-open intervals of the form (lower, upper].
#'
#' The CDF is estimated using methods from the distfromq package. In brief,
#' we use a monotonic cubic spline to interpolate the quantiles, and use
#' members of a specified parametric family (by default, normal distributions)
#' to extrapolate into the tails. See [distfromq::make_p_fn] for details.
#'
#' @return model_out_tbl with pmf forecasts
```

Note that in this proposal, there is not an argument like `to_output_type_id` or `new_output_type_id`.  The `output_type_id` values are contained in the `bin_endpoints` argument.

**Comment by lshandross** [comment]
The function signature generally looks good to me. One question is how we want to handle denoting the limits(?) for adjacent endpoints for each bin. For example, say there are bins A and B for continuous inputs with A<100 and B>=100. How will the differences between <, <=,>, >= be captured within the `bin_endpoints` data frame? Maybe another column is needed?

**Comment by elray1** [comment]
Good question.  I was thinking of enforcing a convention where bins are open on the left and closed on the right... but maybe that's not flexible enough.

Edit: Actually, I think that given our tools/inputs, we have no choice but to enforce a convention where the bins are open on the left and closed on the right.  To get the bin probabilities, the plan will be to evaluate the CDF at the bin end points and take the difference of those probabilities -- which will give probabilities of half-closed intervals of the form (lower, upper].

**Comment by elray1** [comment]
Edited the proposed function signature with that and a couple of other updates.

**Comment by lshandross** [comment]
Okay that's fine with me, and the other changes look good
