### ISSUE TITLE
consider removing the step where we add noise to the provided quantiles

### ISSUE THREAD

**Issue by elray1** [reichlab/idforecastutils#2]
looking at these lines: https://github.com/reichlab/idforecastutils/blob/b137497b0bbe8c59210dcecb37214ad133740d52/R/get_pmf_forecasts_from_quantile.R#L72-L79

I think we don't need this.  Maybe we should double check that after taking these lines out, everything still works ok if there are repeated quantiles (a point mass)

**Comment by lshandross** [comment]
Function works fine without these lines even with repeated quantiles
